# Используем базовый образ Python
FROM python:3.11

# Устанавливаем зависимости
RUN pip install -r requirements.txt

EXPOSE 5051

# Определяем команду запуска сервера при запуске контейнера
CMD ["python", "llm.py"]
