# Используем базовый образ Python
FROM python:3.9

# Устанавливаем зависимости
RUN pip install  --upgrade flask flask_cors requests gradio_client

# Копируем наш серверный код внутрь контейнера
COPY app/server.py .

# Определяем команду запуска сервера при запуске контейнера
CMD ["python", "server.py"]
