# Используем базовый образ Python
FROM python:3.11

# Устанавливаем зависимости
RUN pip install flask llama-cpp-python

# Копируем наш серверный код внутрь контейнера
COPY llm/llm.py .

EXPOSE 5052

# Определяем команду запуска сервера при запуске контейнера
CMD ["python", "llm.py"]
