# Use an official Python runtime as a parent image
# FROM ghcr.io/coqui-ai/tts-cpu
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
# COPY my_tts /app

# Install Rust and other necessary dependencies, including libsndfile
RUN apt-get update && apt-get install -y curl libsndfile1-dev && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . $HOME/.cargo/env && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install any needed dependencies
# RUN pip install Flask flask_cors TTS
RUN . $HOME/.cargo/env && pip install Flask flask_cors soundfile TTS

# Set environment variable to accept the TTS license terms
# ENV COQUI_LICENSE_ACCEPT=1

# Expose the port Flask is running on
EXPOSE 5053

# Define the command to run your Flask application
CMD ["python", "tts.py"]
