# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies
RUN pip install torch TTS Flask gunicorn

# Expose the port Flask is running on
EXPOSE 5053

# Define the command to run your Flask application
CMD ["gunicorn", "-b", "0.0.0.0:5053", "app:app"]
